# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 11:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quserinfo',
            name='blood_pressure',
            field=models.IntegerField(default=110, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(210)]),
        ),
        migrations.AlterField(
            model_name='quserinfo',
            name='smoking_status',
            field=models.CharField(choices=[('NON-SMOKER', 'NON-SMOKER'), ('LIGHT-SMOKER', 'LIGHT-SMOKER'), ('MOD-SMOKER', 'MOD-SMOKER'), ('HEAVY-SMOKER', 'HEAVY-SMOKER')], default='NON-SMOKER', max_length=25),
        ),
        migrations.AlterField(
            model_name='quserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to='calculator.QUser'),
        ),
    ]
